name: AdvancedKits
main: AdvancedKits\Main
version: 5.1.0-10
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: luca28pet
softdepend: ["PiggyCustomEnchants"]
description: Add kits to your server
website: https://github.com/luca28pet/AdvancedKits
commands:
 kit:
  description: Get a kit!
  usage: "/kit <kitName>"
  aliases: [ak, advancedkits]
  permission: advancedkits.command
 akreload:
  descrpition: Reload Kits settings
  usage: "/akreload"
  permission: advancedkits.admin
permissions:
 advancedkits.command:
  description: "Allows the user to run /kit command"
  default: true
 advancedkits.admin:
  description: "Allows to manage admin features"
  default: op
